version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    allow:
      - dependency-type: "direct"
    labels:
      - "composer"
      - "dependencies"
    commit-message:
      prefix: "fix"
      prefix-development: "build"
      include: "scope"
    ignore:
      - dependency-name: "symfony/*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    allow:
      - dependency-type: "direct"
    labels:
      - "npm"
      - "dependencies"
    commit-message:
      prefix: "fix"
      prefix-development: "build"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    allow:
      - dependency-type: "direct"
    labels:
      - "github-actions"
      - "dependencies"
    commit-message:
      prefix: "ci"
      include: "scope"
