name: Split Monorepo

on:
  push:
    branches:
      - '*.x'
    tags:
      - '*'

env:
  PHP_VER: '8.1'
  SPLIT_BRANCH: '1.x'
  ORG_NAME: 'agence-adeliom'

jobs:
  provide_packages_json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VER }}
          coverage: none

      - run: composer config http-basic.gf-composer-proxy.arnaud-ritti.workers.dev licensekey ${{secrets.ORG_GRAVITYFORMS_KEY}}
      - run: composer config http-basic.auth-acf-composer-proxy.pivvenit.net licensekey ${{secrets.ORG_ACF_PRO_KEY}}

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Get package json list
        id: output_data
        run: echo "::set-output name=matrix::$(vendor/bin/monorepo-builder packages-json)"

    outputs:
      matrix: ${{ steps.output_data.outputs.matrix }}

  split_monorepo:
    needs: provide_packages_json
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.provide_packages_json.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: cd .terraform && terraform init

      - name: Terraform Plan
        if: matrix.package != 'lumberjack-project'
        run: cd .terraform && terraform plan -no-color -var='token=${{ secrets.ACCESS_TOKEN }}' -var='repo=${{ matrix.package }}' -var='branch=${{ env.SPLIT_BRANCH }}'

      - name: Terraform Apply
        if: matrix.package != 'lumberjack-project'
        run: cd .terraform && terraform apply -auto-approve -var='token=${{ secrets.ACCESS_TOKEN }}' -var='repo=${{ matrix.package }}' -var='branch=${{ env.SPLIT_BRANCH }}'

      # without tag
      - if: !startsWith(github.ref, 'refs/tags/') && matrix.package != 'lumberjack-project'
        name: Monorepo Split of ${{ matrix.package }}
        uses: symplify/monorepo-split-github-action@2.2
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package_directory: 'packages/${{ matrix.package }}'
          repository_organization: ${{ env.ORG_NAME }}
          repository_name: '${{ matrix.package }}'
          user_name: ${{ github.event.pusher.name }}
          user_email: ${{ github.event.pusher.email }}
          branch: ${{ env.SPLIT_BRANCH }}

      # with tag
      - if: startsWith(github.ref, 'refs/tags/') && matrix.package != 'lumberjack-project'
        name: Monorepo Tagged Split of ${{ matrix.package }}
        uses: symplify/monorepo-split-github-action@2.2
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag: ${GITHUB_REF#refs/tags/}
          package_directory: 'packages/${{ matrix.package }}'
          repository_organization: ${{ env.ORG_NAME }}
          repository_name: '${{ matrix.package }}'
          user_name: ${{ github.event.pusher.name }}
          user_email: ${{ github.event.pusher.email }}
          branch: ${{ env.SPLIT_BRANCH }}

      # without tag
      - if: !startsWith(github.ref, 'refs/tags/') && matrix.package == 'lumberjack-project'
        name: Monorepo Split of ${{ matrix.package }}
        uses: symplify/monorepo-split-github-action@2.2
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package_directory: 'packages/${{ matrix.package }}'
          repository_organization: ${{ env.ORG_NAME }}
          repository_name: '${{ matrix.package }}'
          user_name: ${{ github.event.pusher.name }}
          user_email: ${{ github.event.pusher.email }}
          branch: main

      # with tag
      - if: startsWith(github.ref, 'refs/tags/') && matrix.package == 'lumberjack-project'
        name: Monorepo Tagged Split of ${{ matrix.package }}
        uses: symplify/monorepo-split-github-action@2.2
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag: ${GITHUB_REF#refs/tags/}
          package_directory: 'packages/${{ matrix.package }}'
          repository_organization: ${{ env.ORG_NAME }}
          repository_name: '${{ matrix.package }}'
          user_name: ${{ github.event.pusher.name }}
          user_email: ${{ github.event.pusher.email }}
          branch: main
