name: Split Tests

on:
  pull_request: null
  push: null

jobs:
  provide_packages_json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Get package json list
        id: output_data
        run: echo "::set-output name=matrix::$(vendor/bin/monorepo-builder packages-json --tests)"

    outputs:
      matrix: ${{ steps.output_data.outputs.matrix }}

  split_tests:
    needs: provide_packages_json
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '7.4', '8.0', '8.1' ]
        package: ${{ fromJson(needs.provide_packages_json.outputs.matrix )}}
    name: Split Tests of ${{ matrix.package }} for PHP ${{ matrix.php-versions }}

    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
      - run: rm composer.lock
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - run: vendor/bin/monorepo-builder localize-composer-paths packages/${{ matrix.package }}/composer.json --ansi
      - run: composer update --no-progress --ansi --working-dir packages/${{ matrix.package }}
      - name: Run test suite
        working-directory: packages/${{ matrix.package }}
        run: php vendor/bin/phpunit
